### ISSUE TITLE
Ajouter les documents uploadables

### ISSUE THREAD

**Issue by Jester0027** [E-commerceTechnocite/e-commerce-backend#12]

**Comment by Thalion198** [comment]
![image](https://user-images.githubusercontent.com/80638141/133217675-61ef94a1-25a5-4d75-8efa-ed2784744ae2.png)

**Comment by Thalion198** [comment]
![image](https://user-images.githubusercontent.com/80638141/133219371-9d71ff5f-bb39-4e0b-a56c-2c12d515d88c.png)
